version: 0.2

# The database URLs for the pipeline are below. They will be set using environment variables passed to the buildspec via overrides.
# TEST: "jdbc:postgresql://cs-postgres-test.cz1j1vh9uvuo.us-east-1.rds.amazonaws.com:5432/postgres"
# STAGE: "jdbc:postgresql://cs-postgres-stage.cz1j1vh9uvuo.us-east-1.rds.amazonaws.com:5432/postgres"
# PROD: "jdbc:postgresql://cs-postgres-prod.cz1j1vh9uvuo.us-east-1.rds.amazonaws.com:5432/postgres"

# The username / password secrets are below. They will be set using environment variables passed to the buildspec via overrides. 
# TEST: codebuild/cs/liquibase/demo:USERNAME_CS_TEST / codebuild/cs/liquibase/demo:PASSWORD_CS_TEST
# STAGE: codebuild/cs/liquibase/demo:USERNAME_CS_STAGE / codebuild/cs/liquibase/demo:PASSWORD_CS_STAGE
# PROD: codebuild/cs/liquibase/demo:USERNAME_CS_PROD / codebuild/cs/liquibase/demo:PASSWORD_CS_PROD
    
env:
  variables:
    LIQUIBASE_COMMAND_URL: ""
  secrets-manager:
    LIQUIBASE_COMMAND_USERNAME: 
    LIQUIBASE_COMMAND_PASSWORD: 
    LIQUIBASE_PRO_LICENSE_KEY: codebuild/cs/liquibase/demo:LIQUIBASE_PRO_KEY

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - liquibase --version
  build:
    commands:
      - echo Build started on `date`
      - liquibase --defaultsFile=liquibase.properties validate
      - liquibase --defaultsFile=liquibase.properties tag codebuild-$CODEBUILD_BUILD_NUMBER
      - liquibase --defaultsFile=liquibase.properties status --verbose
      - liquibase --defaultsFile=liquibase.properties updateSql
      - liquibase --defaultsFile=liquibase.properties update
      - liquibase --defaultsFile=liquibase.properties history
      
  post_build:
    commands:
      - liquibase --defaultsFile=liquibase.properties --outputFile=codebuild-$CODEBUILD_BUILD_NUMBER.json snapshot --snapshotFormat=json
      - echo Build completed on `date`
artifacts:
  files:
    - codebuild-$CODEBUILD_BUILD_NUMBER.json

